DROP DATABASE LEAVEDATABASE;
CREATE DATABASE LEAVEDATABASE;
USE LEAVEDATABASE;

CREATE TABLE USER(userId INT AUTO_INCREMENT,
name varchar(20) NOT NULL,
numLeave INT,
CONSTRAINT userId PRIMARY KEY(userId));
